name: Build

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build_android:
    runs-on: android-latest
    steps:
      # Setup
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: aarch64

      - uses: actions/setup-node@v2

      # Install packaging tools
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Install appdmg
        run: npm install -g appdmg

      # Build and package
      - name: Packaging .apk
        run: flutter_distributor package --platform android --targets term.apk --artifact-name "TerminalStudio-${{github.ref_name}}-android.{{ext}}"

      # Publish
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*/*

  
